// ADD GROUPS
export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILED = "ADD_GROUP_FAILED";

// GET GROUPS
export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAILED = "GET_GROUPS_FAILED";

// GET USERS
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";

// GET TEXT CHANNELS
export const GET_TEXTCHANNELS = "GET_TEXTCHANNELS";
export const GET_TEXTCHANNELS_SUCCESS = "GET_TEXTCHANNELS_SUCCESS";
export const GET_TEXTCHANNELS_FAILED = "GET_TEXTCHANNELS_FAILED";

// GET VOICE CHANNELS
export const GET_VOICECHANNELS = "GET_VOICECHANNELS";
export const GET_VOICECHANNELS_SUCCESS = "GET_VOICECHANNELS_SUCCESS";
export const GET_VOICECHANNELS_FAILED = "GET_VOICECHANNELS_FAILED";

// GET LOGO
export const GET_LOGO = "GET_LOGO";
export const GET_LOGO_SUCCESS = "GET_LOGO_SUCCESS";
export const GET_LOGO_FAILED = "GET_LOGO_FAILED";

// GET ADMININFO
export const GET_ADMININFO = "GET_ADMININFO";
export const GET_ADMININFO_SUCCESS = "GET_ADMININFO_SUCCESS";
export const GET_ADMININFO_FAILED = "GET_ADMININFO_FAILED";

// GET ADMINLOGO
export const GET_ADMINLOGO = "GET_ADMINLOGO";
export const GET_ADMINLOGO_SUCCESS = "GET_ADMINLOGO_SUCCESS";
export const GET_ADMINLOGO_FAILED = "GET_ADMINLOGO_FAILED";

// GET CHANNEL IMAGES
export const GET_CHANNELIMAGES = "GET_CHANNELIMAGES";
export const GET_CHANNELIMAGES_SUCCESS = "GET_CHANNELIMAGES_SUCCESS";
export const GET_CHANNELIMAGES_FAILED = "GET_CHANNELIMAGES_FAILED";

// GET CHANNEL IMAGES
export const GET_MUSICPUBLICATIONS = "GET_MUSICPUBLICATIONS";
export const GET_MUSICPUBLICATIONS_SUCCESS = "GET_MUSICPUBLICATIONS_SUCCESS";
export const GET_MUSICPUBLICATIONS_FAILED = "GET_MUSICPUBLICATIONS_FAILED";
